### ISSUE TITLE
TypeError: attn_forward_factory() missing 5 required positional arguments: 'top_k_attention', 'top_k_insert_at', 'top_k_from_layer', 'top_k_to_layer', and 'layer_i'

### ISSUE THREAD

**Issue by canelxie** [Glaciohound/LM-Infinite#7]
When I finish loading llama-7b-chat model and run the code ‘model = convert_llama_model(model, 4096, 10)’， the error occured：
> for layer_i, hidden_layer in enumerate(model.model.layers):
attn = hidden_layer.self_attn
attn.forward = attn_forward_factory(
    attn, True, local_branch, global_branch, local_branch, 0
 )
return model
TypeError: attn_forward_factory() missing 5 required positional arguments: 'top_k_attention', 'top_k_insert_at', 'top_k_from_layer', 'top_k_to_layer', and 'layer_i'

**Comment by canelxie** [comment]
I solved this problem by adding arguments. But there was another error that I couldn't understand. When I converted model and began to infer, the error occurred:
> TypeError: attn_forward_factory.<locals>.limited_distance_forward() got an unexpected keyword argument 'cache_position'

Looking forward to your reply.

**Comment by Glaciohound** [comment]
I appreciate your interest in our work!

As for the first question, I am glad that you solved it. It is probably due to an update (I added support for downstream tasks) that conflicts with the "older" convert_llama_model function.

For the second question, I am not sure but I suspect this is due to the newer Transformer library, which probably passed a new `cache_position` argument to the attention function by LM-Infinite. I will look later but you are encouraged to diagnose in this direction by yourself first.

**Comment by canelxie** [comment]
Thanks for your reply. Your guess is actually right. I fixed this by moving back to `Transformers==4.32.1`

**Comment by Glaciohound** [comment]
@canelxie Hello. I have updated the codes so that the newest Transformer is supported.

Thanks!
